# Tirgul 4
I this session, we will 

In [2]:
# tirgul4
# random
import numpy as np
h,w = 2,4
e = np.random.random((h,w)) 
print("Random Matrix dim: {}X{}".format(h,w))
print(e)

Random Matrix dim: 2X4
[[0.91776581 0.30477725 0.80941284 0.96443814]
 [0.32750364 0.22895042 0.55610141 0.01831752]]


In [3]:
numCols = 6
grades = np.random.randint(70,100,size=(10,numCols))
print("Random Grades:")
print(grades)

Random Grades:
[[90 74 75 94 83 73]
 [70 97 96 95 81 78]
 [76 78 98 90 92 83]
 [74 75 75 80 95 86]
 [76 70 90 90 84 73]
 [75 93 99 80 74 96]
 [73 77 76 89 88 80]
 [71 74 73 78 82 79]
 [73 87 99 88 86 74]
 [92 95 88 71 81 94]]


In [4]:
# Calculate the average of the top 5 grades for each student
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg
top5Avg = top5Avg.reshape(len(top5Avg),1) # for display purpose
print(top5Avg)

[[83.2]
 [89.4]
 [88.2]
 [82.2]
 [82.6]
 [88.6]
 [82. ]
 [77.2]
 [86.8]
 [90. ]]


In [5]:
# let's read it using pandas
import pandas as pd
url = 'https://raw.githubusercontent.com/nlihin/data-analytics/main/datasets/italy-covid-daywise.csv'
covid_df = pd.read_csv(url)
covid_df.tail()

date  new_cases  new_deaths  new_tests
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

### Let's focus on date column

In [6]:
covid_df["date"]

0      2019-12-31
1      2020-01-01
2      2020-01-02
3      2020-01-03
4      2020-01-04
          ...    
243    2020-08-30
244    2020-08-31
245    2020-09-01
246    2020-09-02
247    2020-09-03
Name: date, Length: 248, dtype: object

- Note that date type is object. let's convert it to pandas datetime
- For pandas datetime reference and examples: [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html)
- Video tutorial: [youtube link](https://www.youtube.com/watch?v=UFuo7EHI8zc)


In [7]:
covid_df['date'] = pd.to_datetime(covid_df.date)
covid_df['date']

0     2019-12-31
1     2020-01-01
2     2020-01-02
3     2020-01-03
4     2020-01-04
         ...    
243   2020-08-30
244   2020-08-31
245   2020-09-01
246   2020-09-02
247   2020-09-03
Name: date, Length: 248, dtype: datetime64[ns]

Now we can extract the year,month,day and weekday properties (and muchmore - for ) 

In [18]:
covid_df['year'] = pd.DatetimeIndex(covid_df.date).year
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
covid_df['day'] = pd.DatetimeIndex(covid_df.date).day
covid_df['weekday'] = pd.DatetimeIndex(covid_df.date).weekday
covid_df

date  new_cases  new_deaths  new_tests  month  day  weekday  year
0   2019-12-31       2019         0.0        NaN     12   31        1  2019
1   2020-01-01       2020         0.0        NaN      1    1        2  2020
2   2020-01-02       2020         0.0        NaN      1    2        3  2020
3   2020-01-03       2020         0.0        NaN      1    3        4  2020
4   2020-01-04       2020         0.0        NaN      1    4        5  2020
..         ...        ...         ...        ...    ...  ...      ...   ...
243 2020-08-30       2020         1.0    53541.0      8   30        6  2020
244 2020-08-31       2020         4.0    42583.0      8   31        0  2020
245 2020-09-01       2020         6.0    54395.0      9    1        1  2020
246 2020-09-02       2020         8.0        NaN      9    2        2  2020
247 2020-09-03       2020         6.0        NaN      9    3        3  2020

[248 rows x 8 columns]

Now we can present rows of specific dates, for example only August:

In [9]:
covid_df_august = covid_df[covid_df.month == 8]
covid_df_august.head()

date  new_cases  new_deaths  new_tests  month  day  weekday
214 2020-08-01       2020         9.0    31905.0      8    1        5
215 2020-08-02       2020         5.0    24496.0      8    2        6
216 2020-08-03       2020         8.0    13467.0      8    3        0
217 2020-08-04       2020        12.0    23491.0      8    4        1
218 2020-08-05       2020         5.0    29739.0      8    5        2

### Extract the subset of columns to be aggregated

In [10]:
covid_df_august_metrics = covid_df_august[['new_cases', 'new_deaths', 'new_tests']]

# Get the column-wise sum
covid_august_totals = covid_df_august_metrics.sum()
covid_august_totals

new_cases       62620.0
new_deaths        345.0
new_tests     1098704.0
dtype: float64

We can do the same for mean 

In [11]:
covid_df_august_metrics.mean()

new_cases      2020.000000
new_deaths       11.129032
new_tests     35442.064516
dtype: float64

Or median

In [12]:
covid_df_august_metrics.median()

new_cases      2020.0
new_deaths        6.0
new_tests     31905.0
dtype: float64

### The *groupby* command

In [13]:
# let's sum:
covid_month_df_sum = covid_df.groupby('month')[['new_cases', 'new_deaths', 'new_tests']].sum()
covid_month_df_sum
# deaths per months graphs
# hist cborn

new_cases  new_deaths  new_tests
month                                  
1          62620         0.0        0.0
2          58580        21.0        0.0
3          62620     11570.0        0.0
4          60600     16091.0   419591.0
5          62620      5658.0  1078720.0
6          60600      1404.0   830354.0
7          62620       388.0   797692.0
8          62620       345.0  1098704.0
9           6060        20.0    54395.0
12          2019         0.0        0.0

We could do the same for mean or any other stats

In [14]:
covid_df.groupby('month')[['new_cases', 'new_deaths', 'new_tests']].mean()

new_cases  new_deaths     new_tests
month                                     
1           2020    0.000000           NaN
2           2020    0.724138           NaN
3           2020  373.225806           NaN
4           2020  536.366667  38144.636364
5           2020  182.516129  34797.419355
6           2020   46.800000  27678.466667
7           2020   12.516129  25732.000000
8           2020   11.129032  35442.064516
9           2020    6.666667  54395.000000
12          2019    0.000000           NaN

### Print todays date in pandas:

In [15]:
import pandas as pd
from datetime import date # get python datetime
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-06-01 00:00:00


## Self Learning:.
1. calculate total deaths at May in attached *'italy-covid-daywise.csv'* fuke
1. python pandas datetime excercises (with solutions): [Link to exercises](https://www.w3resource.com/python-exercises/pandas/datetime/index.php)

## Solution 2

In [16]:
import pandas as pd
covid_df = pd.read_csv('italy-covid-daywise.csv')
covid_df['date'] = pd.to_datetime(covid_df.date)
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
totalDeathsInMay = covid_df[covid_df.month == 5]['new_deaths'].sum()
print('total deaths in May: ',totalDeathsInMay)

FileNotFoundError: [Errno 2] No such file or directory: 'italy-covid-daywise.csv'